outfile = open('portfolio_website.html', 'w')
userName = input("Enter name : ")
userDesc = input("Enter a brief description : \n")
outfile.write('<html>\n')
outfile.write('<head>\n')
outfile.write('</head>\n')
outfile.write('<body>\n')
outfile.write('<center>\n')
outfile.write('<h1>')
outfile.write(userName)
outfile.write('</h1>\n')
outfile.write('</center>\n')
outfile.write('<hr>\n')
outfile.write(userDesc + '\n')
outfile.write('<hr>\n')
outfile.write('</body>\n')
outfile.write('</html>\n')
print("Web page created...")
outfile.close()